# Generated by Django 4.1.7 on 2023-02-20 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=100)),
                ('Course_Duration', models.IntegerField(default=0)),
                ('Total_Tasks', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Training-Courses',
            },
        ),
        migrations.CreateModel(
            name='CoursesTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_No', models.IntegerField(default=0)),
                ('Task_Content', models.CharField(max_length=255)),
                ('Course_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='TaskDashboard.courses')),
            ],
            options={
                'db_table': 'Courses-Tasks',
            },
        ),
    ]
