# Generated by Django 4.1.7 on 2023-02-22 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TaskDashboard', '0003_delete_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certificate_Link', models.CharField(max_length=255)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskDashboard.courses')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Student-Profile',
            },
        ),
    ]
