# Generated by Django 4.1.7 on 2023-02-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskDashboard', '0004_studentsprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsprofile',
            name='College_Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentsprofile',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentsprofile',
            name='Certificate_Link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
