# Generated by Django 4.1.7 on 2023-02-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskDashboard', '0005_studentsprofile_college_name_studentsprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsprofile',
            name='Contact_No',
            field=models.BigIntegerField(default=0),
        ),
    ]
